<?
    global $language_array;
    $language_array = array(
    'Add'               =>'Tambah',
    'Go'                =>'Mulai',
    'Indicates required fields'=>'harus diisi',
    'Save'              =>'Simpan',
    'Cancel'            =>'Tidak Jadi',
    'switch to table'   =>'Tukar ke bentuk tabel',
    "You're logged as"  =>'Anda login sebagai',
    'Search'            =>'Cari',
    'in'                =>'di',
    'The search'        =>'Pencarian',
    'returns no record' =>'tidak mengembalikan data',
    'Reset Search'      =>'Reset Pencarian',
    'found'             =>'menemukan',
    'record(s)'         =>'baris',
    'switch to form'    =>'Tukar ke bentuk form',
    'Check All'         =>'Tick semuanya',
    'Uncheck All'       =>'Hapus semua tick',
    'With selected'     =>'Pada pilihan',
    'Do'                =>'Lakukan',
    'has been deleted'  =>'telah dihapus',
    'Generate CSV for input (Comma)'=>'Buatkan CSV untuk input (koma)',
    'Generate CSV for input (Tab)'  =>'Buatkan CSV untuk input (tab)',
    'Enter CSV for input'           =>'Entry CSV untuk input',
    'Create table'      =>'Buatkan tabel',
    'Merge changes'     =>'Gabung perubahan',
    'Drop table'        =>'Hapus tabel dari database',
    'Purge table'       =>'Kosongkan tabel',
    'Home'              =>'Awal',
    'Manage Modules'    =>'Atur Modul',
    'Sequence Generator'=>'Bilangan Berurut',
    'User Manager'      =>'Atur User',
    'System'            =>'Sistem',
    'All fields'        =>'Semua field',
    'Edit'              =>'Modifikasi',
    'New'               =>'Baru',
    'Delete'            =>'Hapus',
    'Duplicate'         =>'Duplikasi',
    'View'              =>'Lihat',
    'Generate CSV'      =>'Buatkan CSV',
    'Are you sure you want to delete'=>'Anda yakin ingin menghapus',
    'You need to pick at least one row'=>'Anda perlu memilih paling tidak satu baris',
    'Delete record'     =>'Hapus data',
    'Pages'             =>'Halaman',
    'Show All'          =>'Tampilkan Semua',
    'is required'       =>'harus diisi',
    'Error in form'     =>'Kesalahan pada isian',
    'Table has no'      =>'Belum ada',
    'Command'           =>'Perintah',
    'Continue'          =>'Lanjut',
    // manage module
    'Are you sure'      =>'Anda yakin',

    // news module
    'Browse monthly'    =>'Lacak bulanan',
    'month_array'       =>array('','Januari','Pebruari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','Nopember','Desember'),
    'day_array'         =>array('Senin','Selasa','Rabu','Kamis','Jum\'at','Sabtu','Minggu'),
    'News'             =>'Berita',
    'Title'             =>'Judul',
    'Description'             =>'Deskripsi',
    'Summary'           =>'Kesimpulan',
    'Body'              =>'Badan',
    'Category'          =>'Kategori',
    'Author'            =>'Penulis',
    'Creation Date'     =>'Tanggal Cipta',
    'News category'     =>'Kategori berita',

    //directory module
    'Directory'=>'Direktori',
    'Directory entry'=>'Entri direktori',
    'Name'  =>'Nama',
    'Parent'=>'Bapak',
    'Address'=>'Alamat',
    'City'=>'Kota',
    'Zip code'=>'Kode pos',
    'Province'=>'Propinsi',
    'Head of company'=>'Nama pimpinan',

    // unit
    'record'        =>'data',
    'news'          =>'berita',
    'category'      =>'kategori',
    'module'        =>'modul',
    'user'        =>'pengguna',
    );

?>