<?
/* admin frontpage
 copyright 2004 - dody suria wijaya, dsw software house - contact: dswsh@plasa.com */

include_once(APP_INCLUDE_ROOT.'/auth.inc.php');
include_once(APP_INCLUDE_ROOT.'/dbgrid.class.php');
require_once( LOG4PHP_DIR . '/LoggerManager.php' ); //log4php

class jalan_lateral extends TableManager {
    var $db_table, $properties;

    function jalan_lateral() {
        parent::TableManager(); # must call base class
		$this->_logger =& LoggerManager::getLogger('Jalan Lateral');

        global $html_title;
        $this->title = 'Jalan Lateral';
        $html_title = $this->title;
        $this->db_table = $GLOBALS['dbpre'].'jalan_lateral_tab';

		$this->properties['kode_cabang'] = new Prop(array('label'=>'Cabang','length'=>4,'colname'=>'kode_cabang', 'required'=>True, 'is_key'=>True,'inputtype'=>'combobox','enumerate'=>'cabang'));
		$this->properties['kode_jalan'] = new Prop(array('label'=>'Kode jalan','length'=>4,'colname'=>'kode_jalan', 'required'=>True, 'is_key'=>True,'inputtype'=>'combobox','enumerate'=>'jalan'));
		$this->properties['kode_ruas'] = new Prop(array('label'=>'Kode Ruas','length'=>4,'colname'=>'kode_ruas', 'required'=>True, 'is_key'=>True));
		$this->properties['sta_awal'] = new Prop(array('label'=>'STA Awal','colname'=>'sta_awal','length'=>17,'required'=>False,'is_key'=>true));
		$this->properties['sta_akhir'] = new Prop(array('label'=>'STA Akhir','colname'=>'sta_akhir','length'=>17,'required'=>False,'is_key'=>false));
		$this->properties['lebar'] = new Prop(array('label'=>'Lebar','colname'=>'lebar','length'=>15));
        $this->properties['kode_bahan_lapisan_permukaan'] = new Prop(array('label'=>'Kode Bahan Lapisan Permukaan','length'=>10,'colname'=>'kode_bahan_lapisan_permukaan', 'required'=>True, 'is_key'=>false,'inputtype'=>'combobox','enumerate'=>'bahan_lapisan_permukaan'));
		$this->properties['kode_lapisan_perkerasan'] = new Prop(array('label'=>'Kode Lapisan Perkerasan','length'=>10,'colname'=>'kode_lapisan_perkerasan', 'required'=>True, 'is_key'=>false,'inputtype'=>'combobox','enumerate'=>'lapisan_perkerasan'));
		$this->properties['kode_tipe_lapisan_permukaan'] = new Prop(array('label'=>'Kode Tipe Lapisan Permukaan','length'=>10,'colname'=>'kode_tipe_lapisan_permukaan', 'required'=>True, 'is_key'=>false,'inputtype'=>'combobox','enumerate'=>'tipe_lapisan_permukaan'));
		$this->properties['kode_tipe_perkerasan'] = new Prop(array('label'=>'Kode Tipe Perkerasan','length'=>10,'colname'=>'tipe_perkerasan', 'required'=>True, 'is_key'=>false,'inputtype'=>'combobox','enumerate'=>'tipe_perkerasan'));

		//$this->properties['sistem_operasi'] = new Prop(array('label'=>'Sistem Operasi','colname'=>'sistem_operasi','updatable'=>True,'insertable'=>True));
		//$this->properties['kecepatan_rencana'] = new Prop(array('label'=>'Kecepatan Rencana','colname'=>'kecepatan_rencana','updatable'=>True,'insertable'=>True));
		//$this->properties['daerah_milik_jalan'] = new Prop(array('label'=>'Daerah Milik Jalan','colname'=>'daerah_milik_jalan','updatable'=>True,'insertable'=>True));
		//$this->properties['penampang_melintang'] = new Prop(array('label'=>'Penampang Melintang','colname'=>'penampang_melintang','browse_maxchar'=>30));
		//$this->properties['jenis_perkerasan'] = new Prop(array('label'=>'Jenis Perkerasan','colname'=>'jenis_perkerasan','updatable'=>True,'insertable'=>True));
		//$this->properties['simpang_susun'] = new Prop(array('label'=>'Simpang Susun','colname'=>'simpang_susun','browse_maxchar'=>30));




        $this->enum_keyval = array('kode_ruas','nama');

        //$this->grid_command[] = array('attach','Attach to newsletter...');
        //$this->grid_command[] = array('','-----');


        $prog->must_authenticated = True;

        #~ if ($_SESSION['login_level'] > 1)
            #~ $this->db_where="author='{$_SESSION['login_user']}'";
        #~ $this->enum_keyval = array('rowid','nama');
        $this->browse_mode = 'form';

    }

    function go() { // called inside main content
        //debug($this);

        //LoggerNDC::push('NDC generated by TestTest::testLog()');
    /*
        $logger->debug('Try the debug statement');
        $logger->info('Try the info statement');
        $logger->warn('Try the debug warn');
        $logger->error('Try the statement Error');
        $logger->fatal('Try the fatal statement');
	*/
		#~ echo "<h3>Tahapan Kerjasama</h3>";
        $this->basic_handler();

    }



    function insert($rowindex) {
    //    $this->ds->create_date[$rowindex] = 'Now()';
      //  $this->ds->author[$rowindex] = $_SESSION['login_user'];
        parent::insert($rowindex);
    }

    function showgrid() {

        parent::showgrid();
    }

    function check_del() {
        # for normal user, make sure they can only modify their own
        if ($_SESSION['login_level'] > 1) {
            foreach ($this->_rowid as $rowid) {
                if (!$this->get_row(array('rowid'=>$rowid,'author'=>$_SESSION['login_user'])))
                    echo '<p>You may not modify this row</p>';
                    return False;
            }
        }
        return True;
    }

    function prepare_update() {
        # for normal user, make sure they can only modify their own
        if ($_SESSION['login_level'] > 1) {
            foreach ($this->_rowid as $rowid) {
                if (!$this->get_row(array('rowid'=>$rowid,'author'=>$_SESSION['login_user']))) {
                    echo '<p>You may not modify this row</p>';
                    return False;
                }
            }
        }
        return True;
    }



}

?>