<?
/* admin frontpage
 copyright 2004 - dody suria wijaya, dsw software house - contact: dswsh@plasa.com */

include_once(APP_INCLUDE_ROOT.'/auth.inc.php');
include_once(APP_INCLUDE_ROOT.'/dbgrid.class.php');
require_once( LOG4PHP_DIR . '/LoggerManager.php' ); //log4php

class kota extends TableManager {
    var $db_table, $properties;

    function kota() {
        parent::TableManager(); # must call base class
		$this->_logger =& LoggerManager::getLogger('kota');

        global $html_title;
        $this->title = 'Kota';
        $html_title = $this->title;
        $this->db_table = $GLOBALS['dbpre'].'kota_tab';

		$this->properties['kode_propinsi'] = new Prop(array('label'=>'Propinsi','length'=>2,'colname'=>'kode_propinsi', 'required'=>True, 'is_key'=>True,'inputtype'=>'combobox','enumerate'=>'propinsi'));
		$this->properties['kode_kota'] = new Prop(array('label'=>'Kode Kota','length'=>7,'colname'=>'kode_kota', 'required'=>True, 'is_key'=>True));
		$this->properties['nama_kota'] = new Prop(array('label'=>'Kota','colname'=>'nama_kota','length'=>45,'required'=>True,'is_key'=>false));
		$this->properties['luas_wilayah'] = new Prop(array('label'=>'Luas Wilayah','colname'=>'luas_wilayah','length'=>25,'required'=>False,'is_key'=>false));
		$this->properties['jumlah_penduduk'] = new Prop(array('label'=>'Jumlah Penduduk','colname'=>'jumlah_penduduk','length'=>25,'required'=>False,'is_key'=>false));
		$this->properties['status_kota'] = new Prop(array('label'=>'Status Kota','colname'=>'status_kota','length'=>1,'hidden'=>True,'required'=>False,'is_key'=>false));


        $this->enum_keyval = array('kode_kota','nama_kota');

        //$this->grid_command[] = array('attach','Attach to newsletter...');
        //$this->grid_command[] = array('','-----');


        $prog->must_authenticated = True;

        #~ if ($_SESSION['login_level'] > 1)
            #~ $this->db_where="author='{$_SESSION['login_user']}'";
        #~ $this->enum_keyval = array('rowid','nama');
        $this->browse_mode = 'form';

    }

    function go() { // called inside main content
        //debug($this);
	
        //LoggerNDC::push('NDC generated by TestTest::testLog()');
    /*
        $logger->debug('Try the debug statement');
        $logger->info('Try the info statement');
        $logger->warn('Try the debug warn');
        $logger->error('Try the statement Error');
        $logger->fatal('Try the fatal statement');
	*/
		#~ echo "<h3>Tahapan Kerjasama</h3>";
        $this->basic_handler();

    }



    function insert($rowindex) {
    //    $this->ds->create_date[$rowindex] = 'Now()';
      //  $this->ds->author[$rowindex] = $_SESSION['login_user'];
        parent::insert($rowindex);
    }

    function showgrid() {

        parent::showgrid();
    }

    function check_del() {
        # for normal user, make sure they can only modify their own
        if ($_SESSION['login_level'] > 1) {
            foreach ($this->_rowid as $rowid) {
                if (!$this->get_row(array('rowid'=>$rowid,'author'=>$_SESSION['login_user'])))
                    echo '<p>You may not modify this row</p>';
                    return False;
            }
        }
        return True;
    }

    function prepare_update() {
        # for normal user, make sure they can only modify their own
        if ($_SESSION['login_level'] > 1) {
            foreach ($this->_rowid as $rowid) {
                if (!$this->get_row(array('rowid'=>$rowid,'author'=>$_SESSION['login_user']))) {
                    echo '<p>You may not modify this row</p>';
                    return False;
                }
            }
        }
        return True;
    }



}

?>