<html>
<head>
<title>ASPN: Python Cookbook</title>
<link rel="stylesheet" type="text/css" href="clean.css">
</head>
<body>
<h1>ASPN: Python Cookbook collection</h1>

<p>All of these python codes was retrieved from Activestate Python Cookbook website, self-built python scripts to ripped the content into MySql, 
and prep into Microsft Help's ready htmls and its coresponding table of content. Finally compiled into compressed .chm using the free Microsoft HTML Help Workshop.
4.74.8702.0. Happy reading! :) -- <a href=mailto:dswsh@plasa.com>Dody Wijaya</a>

<h3>Content</h3>
<p>
%(sources_link)s
<hr>
generated by <i>cookbook parser</i> - <a href=http://dsw.gesit.com>dsw s/h 2004</a>
</body>
</html>