<html>
<head>
<title>%(title)s</title>
<link rel="stylesheet" type="text/css" href="aspn.css">
</head>
<body>
<small><a href='main.html'>Up</a></small>
<h1>%(category)s</h1>
<p>
%(sources_link)s
<hr>
generated by <i>cookbook parser</i> - <a href=http://dsw.gesit.com>dsw s/h 2004</a>
</body>
</html>