<html>
<head>
<title>ASPN: Python Cookbook</title>
<link rel="stylesheet" type="text/css" href="aspn.css">
</head>
<body>
<h1>ASPN: Python Cookbook collection</h1>

<p>These python codes was retrieved from <a href='http://aspn.activestate.com/ASPN/Cookbook/Python'>Activestate Python Cookbook</a>, self-built python scripts to grabbed, index, parse, and ripped and prep into Microsfut Help's ready htmls and its coresponding table of content. Finally compiled into compressed .chm using the free Microsoft HTML Help Workshop.
4.74.8702.0. Happy reading from Indonesia! -- <a href="mailto:dodysw@gmail.com">Dody Suria Wijaya</a>

<h3>Content</h3>
<p>
%(sources_link)s
<hr>
generated by <i>cookbook parser</i> - <a href=http://dsw.gesit.com>dsw s/h 2004</a>
</body>
</html>