<html>
<head>
<title>%(title)s</title>
<link rel="stylesheet" type="text/css" href="aspn.css">
</head>
<body>
<small><a href='%(category)s.html'>Up</a></small>
<h1>%(title)s</h1>
<h3>by %(submitter)s</h3>
<small>Last update: %(lastupdate)s, Version: %(version)s, Category: %(category)s</small>
<p>%(description)s</p>
<br>
<table><tr><td>
%(source)s
</td></tr></table>
<p><b>Discussion:</b></p>
%(discussion)s
%(comment)s
<hr>
generated by <i>cookbook parser</i> - <a href=http://dsw.gesit.com>dody suria wijaya's software house, 2004</a>
<small>%(filename)s</small>
</body>
</html>